### ISSUE TITLE
Small question about pcgamingwiki theme

### ISSUE THREAD

**Issue by MoneyAllDay** [jwortmann/stylus-themes#1]
Is there any reason for ":root" to be outside of the "@-moz-document domain" brackets?

[It makes the style active on every other page.](https://i.imgur.com/VbiGKqb.png)

**Comment by jwortmann** [comment]
There is no particular reason, I just didn't notice it because I used the same values for all styles I use with the plugin. Thanks for letting me know! I will fix it.
